package U65Classmate;

# This file is auto-generated by program './make-U65Classmates-pm.pl'.  Edits will be lost.

use base qw(Class::Accessor);

my @fields
  = qw(
        sqdn
        preferred_sqdn
        graduated
        last
        first

        middle
        suff
        nickname
        email
        email2

        email3
        home_phone
        cell_phone
        work_phone
        fax_phone

        address1
        address2
        address3
        city
        state

        zip
        country
        foreign_zip
        spouse_first
        spouse_last

        spouse_email
        spouse_cell
        family_poc
        poc_title
        poc_first

        poc_last
        reunion50
        show_on_map
        hide_data
        buzz_off

        csrep_updated
        csrep_comments
        deceased
        burial_site
        highest_rank

        service
        cert_installed
        operating_system
     );

U65Classmate->follow_best_practice;
U65Classmate->mk_accessors(@fields);

# get and initialize a new object by using a hash; e.g.,
# my $obj = U65Classmate->new($hash_ref);

sub print_csv_line {
  my $self = shift @_;
  my $fp   = shift @_;
  my $key  = shift @_;

  my $val;

  print $fp "$key";

  $val = $self->get_sqdn();
  print $fp ",$val";
  $val = $self->get_preferred_sqdn();
  print $fp ",$val";
  $val = $self->get_graduated();
  print $fp ",$val";
  $val = $self->get_last();
  print $fp ",$val";
  $val = $self->get_first();
  print $fp ",$val";

  $val = $self->get_middle();
  print $fp ",$val";
  $val = $self->get_suff();
  print $fp ",$val";
  $val = $self->get_nickname();
  print $fp ",$val";
  $val = $self->get_email();
  print $fp ",$val";
  $val = $self->get_email2();
  print $fp ",$val";

  $val = $self->get_email3();
  print $fp ",$val";
  $val = $self->get_home_phone();
  print $fp ",$val";
  $val = $self->get_cell_phone();
  print $fp ",$val";
  $val = $self->get_work_phone();
  print $fp ",$val";
  $val = $self->get_fax_phone();
  print $fp ",$val";

  $val = $self->get_address1();
  print $fp ",$val";
  $val = $self->get_address2();
  print $fp ",$val";
  $val = $self->get_address3();
  print $fp ",$val";
  $val = $self->get_city();
  print $fp ",$val";
  $val = $self->get_state();
  print $fp ",$val";

  $val = $self->get_zip();
  print $fp ",$val";
  $val = $self->get_country();
  print $fp ",$val";
  $val = $self->get_foreign_zip();
  print $fp ",$val";
  $val = $self->get_spouse_first();
  print $fp ",$val";
  $val = $self->get_spouse_last();
  print $fp ",$val";

  $val = $self->get_spouse_email();
  print $fp ",$val";
  $val = $self->get_spouse_cell();
  print $fp ",$val";
  $val = $self->get_family_poc();
  print $fp ",$val";
  $val = $self->get_poc_title();
  print $fp ",$val";
  $val = $self->get_poc_first();
  print $fp ",$val";

  $val = $self->get_poc_last();
  print $fp ",$val";
  $val = $self->get_reunion50();
  print $fp ",$val";
  $val = $self->get_show_on_map();
  print $fp ",$val";
  $val = $self->get_hide_data();
  print $fp ",$val";
  $val = $self->get_buzz_off();
  print $fp ",$val";

  $val = $self->get_csrep_updated();
  print $fp ",$val";
  $val = $self->get_csrep_comments();
  print $fp ",$val";
  $val = $self->get_deceased();
  print $fp ",$val";
  $val = $self->get_burial_site();
  print $fp ",$val";
  $val = $self->get_highest_rank();
  print $fp ",$val";

  $val = $self->get_service();
  print $fp ",$val";
  $val = $self->get_cert_installed();
  print $fp ",$val";
  $val = $self->get_operating_system();
  print $fp ",$val";

  print $fp "\n";
} # print_csv_line

sub get_field_values {
  my $self = shift @_;
  my $key  = shift @_;

  my @vals = ($key);

  push @vals, $self->get_sqdn();
  push @vals, $self->get_preferred_sqdn();
  push @vals, $self->get_graduated();
  push @vals, $self->get_last();
  push @vals, $self->get_first();

  push @vals, $self->get_middle();
  push @vals, $self->get_suff();
  push @vals, $self->get_nickname();

  # stop if he wants to hide
  if ($self->get_hide_data()) {
    my $val = "(data restricted, contact DBA)";
    push @vals, $val; # in place of 'email'

    # need 34 more vals
    for (1..34) {
      push @vals, '';
    }
    return @vals;
  }

  push @vals, $self->get_email();

  push @vals, $self->get_email2();       # line 202
  push @vals, $self->get_email3();
  push @vals, $self->get_home_phone();
  push @vals, $self->get_cell_phone();
  push @vals, $self->get_work_phone();
  push @vals, $self->get_fax_phone();
  push @vals, $self->get_address1();
  push @vals, $self->get_address2();
  push @vals, $self->get_address3();
  push @vals, $self->get_city();
  push @vals, $self->get_state();
  push @vals, $self->get_zip();
  push @vals, $self->get_country();
  push @vals, $self->get_foreign_zip();
  push @vals, $self->get_spouse_first();
  push @vals, $self->get_spouse_last();
  push @vals, $self->get_spouse_email();
  push @vals, $self->get_spouse_cell();
  push @vals, $self->get_family_poc();
  push @vals, $self->get_poc_title();
  push @vals, $self->get_poc_first();
  push @vals, $self->get_poc_last();
  push @vals, $self->get_reunion50();
  push @vals, $self->get_show_on_map();
  push @vals, $self->get_hide_data();
  push @vals, $self->get_buzz_off();
  push @vals, $self->get_csrep_updated();
  push @vals, $self->get_csrep_comments();
  push @vals, $self->get_deceased();
  push @vals, $self->get_burial_site();
  push @vals, $self->get_highest_rank();
  push @vals, $self->get_service();
  push @vals, $self->get_cert_installed();
  push @vals, $self->get_operating_system(); # line 235

  return @vals;
} # get_field_values

##### obligatory 1 (true) return for a package #####
1;
